name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: NickelMenu
    runs-on: ubuntu-latest
    container: ghcr.io/pgaskin/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Patch
      run: |
        git remote add appstream https://github.com/pgaskin/NickelMenu.git
        git fetch appstream pull/167/head:pr-167
        git checkout pr-167
    - name: Build
      run: make all koboroot
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: NickelMenu
        path: KoboRoot.tgz
